# Upptime configuration for Green Orbit Digital
owner: greenorbitspace
repo: status.greenorbit.space # The repository name for the status page

# List of sites to monitor
sites:
  - name: Green Orbit Website
    url: https://greenorbit.space
    emoji: "🌍"

  - name: Hub
    url: https://hub.greenorbit.space
    emoji: "🧩"

  - name: API
    url: https://api.greenorbit.space
    emoji: "⚡"

  - name: SDGs Portal
    url: https://sdgs.greenorbit.space
    emoji: "🎯"

  - name: Assets
    url: https://assets.greenorbit.space
    emoji: "📦"

  - name: Analytics
    url: https://analytics.greenorbit.space
    emoji: "📊"

  - name: Docs
    url: https://docs.greenorbit.space
    emoji: "📄"

  - name: Blog
    url: https://blog.greenorbit.space
    emoji: "📝"

# Optional: Frequency of uptime checks (default is every 5 minutes)
cron: "*/5 * * * *"

# Optional: GitHub Pages branch for deployment
pages:
  branch: gh-pages

# Optional: Default emojis for incidents
defaults:
  emoji: "✅"
  emojiDown: "❌"
  emojiWarning: "🟧"