# .github/workflows/deploy.yml
name: "Upptime Deploy"

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 5 minutes; adjust if needed
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Upptime checks
      - name: Run Upptime
        run: npm run uptime

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          user_name: "GitHub Actions"
          user_email: "actions@github.com"